# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170913_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='m2m',
            field=models.ManyToManyField(null=True, to='app01.Role'),
        ),
    ]
