# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20170913_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='m2m',
            field=models.ManyToManyField(to='app01.Role', verbose_name='角色'),
        ),
    ]
